version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: event-service-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=event-service
    networks:
      - event-network

  mongo-express:
    image: mongo-express:latest
    container_name: event-service-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - event-network

volumes:
  mongodb_data:

networks:
  event-network:
    driver: bridge 